//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chemist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chemist()
        {
            this.ChemistPayOuts = new HashSet<ChemistPayOut>();
        }
    
        public int Id { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsApproved { get; set; }
        public string ChemistName { get; set; }
        public string ShopName { get; set; }
        public string MobileNumber { get; set; }
        public string EmailId { get; set; }
        public string LicenceNumber { get; set; }
        public string Password { get; set; }
        public int StateMaster_Id { get; set; }
        public int CityMaster_Id { get; set; }
        public string Location { get; set; }
        public string GSTNumber { get; set; }
        public int AdminLogin_Id { get; set; }
        public string PAN { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lng { get; set; }
        public Nullable<int> Location_Id { get; set; }
        public Nullable<System.DateTime> LicenseValidity { get; set; }
        public Nullable<int> Vendor_Id { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string Certificateimg { get; set; }
        public string CityNames { get; set; }
        public string LocationName { get; set; }
        public bool IsCheckedTermsCondition { get; set; }
        public string ChemistId { get; set; }
        public string RefId { get; set; }
        public string PinCode { get; set; }
        public string ConfirmPassword { get; set; }
        public string LicenceImage { get; set; }
        public string About { get; set; }
    
        public virtual AdminLogin AdminLogin { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChemistPayOut> ChemistPayOuts { get; set; }
    }
}
