//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChemistPayOut
    {
        public int Id { get; set; }
        public Nullable<int> Chemist_Id { get; set; }
        public double Amount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<bool> IsGenerated { get; set; }
        public Nullable<int> BankdetailsId { get; set; }
    
        public virtual Chemist Chemist { get; set; }
    }
}
