//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityTemp
    {
        public int Id { get; set; }
        public string CityName { get; set; }
        public Nullable<int> Login_Id { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<int> State_Id { get; set; }
    
        public virtual AdminLogin AdminLogin { get; set; }
        public virtual StateMaster StateMaster { get; set; }
    }
}
