//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.CancelledAppointments = new HashSet<CancelledAppointment>();
        }
    
        public int Id { get; set; }
        public bool IsDeleted { get; set; }
        public string DoctorName { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string EmailId { get; set; }
        public int StateMaster_Id { get; set; }
        public int CityMaster_Id { get; set; }
        public string Location { get; set; }
        public string LicenceImage { get; set; }
        public string LicenceNumber { get; set; }
        public string ClinicName { get; set; }
        public int Department_Id { get; set; }
        public int Specialist_Id { get; set; }
        public double Fee { get; set; }
        public string Password { get; set; }
        public bool IsApproved { get; set; }
        public int AdminLogin_Id { get; set; }
        public string PAN { get; set; }
        public string AadharNumber { get; set; }
        public string AadharImage { get; set; }
        public Nullable<int> Vendor_Id { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<int> SlotTime { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<System.DateTime> LicenseValidity { get; set; }
        public string PinCode { get; set; }
        public string AadharImage2 { get; set; }
        public string PanImage { get; set; }
        public Nullable<int> HospitalId { get; set; }
        public string DoctorId { get; set; }
        public Nullable<bool> IsCheckedTermsCondition { get; set; }
        public Nullable<System.TimeSpan> StartTime2 { get; set; }
        public Nullable<System.TimeSpan> EndTime2 { get; set; }
        public Nullable<int> SlotTime2 { get; set; }
        public string RefId { get; set; }
        public Nullable<int> Experience { get; set; }
        public string About { get; set; }
        public string Disease { get; set; }
        public string Qualification { get; set; }
        public string RegistrationNumber { get; set; }
        public string SignaturePic { get; set; }
        public Nullable<double> VirtualFee { get; set; }
        public Nullable<int> Day_Id { get; set; }
        public Nullable<bool> IsBankUpdateApproved { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CancelledAppointment> CancelledAppointments { get; set; }
    }
}
