//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Driver()
        {
            this.TravelMasters = new HashSet<TravelMaster>();
            this.TravelRecordMasters = new HashSet<TravelRecordMaster>();
            this.DriverComplaints = new HashSet<DriverComplaint>();
            this.DriverLocations = new HashSet<DriverLocation>();
        }
    
        public int Id { get; set; }
        public bool IsDeleted { get; set; }
        public string DriverName { get; set; }
        public string MobileNumber { get; set; }
        public string EmailId { get; set; }
        public int StateMaster_Id { get; set; }
        public Nullable<int> CityMaster_Id { get; set; }
        public string Location { get; set; }
        public string DriverImage { get; set; }
        public string DlImage { get; set; }
        public string DlNumber { get; set; }
        public Nullable<System.DateTime> DlValidity { get; set; }
        public string Password { get; set; }
        public int AdminLogin_Id { get; set; }
        public bool IsApproved { get; set; }
        public string PAN { get; set; }
        public string AadharNumber { get; set; }
        public string AadharImage { get; set; }
        public Nullable<int> Vendor_Id { get; set; }
        public Nullable<bool> IsVerifiedByPolice { get; set; }
        public string VerificationDoc { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<int> VehicleType_Id { get; set; }
        public string PinCode { get; set; }
        public string AadharImage2 { get; set; }
        public string DlImage1 { get; set; }
        public string DlImage2 { get; set; }
        public string DlImage3 { get; set; }
        public string PanImage { get; set; }
        public string DriverId { get; set; }
        public Nullable<bool> IsCheckedTermsCondition { get; set; }
        public string RefId { get; set; }
        public string VehicleName { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Paidamount { get; set; }
        public string Status { get; set; }
        public string BranchName { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lang { get; set; }
        public Nullable<int> Charge { get; set; }
        public Nullable<bool> IsBankUpdateApproved { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelMaster> TravelMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelRecordMaster> TravelRecordMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriverComplaint> DriverComplaints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriverLocation> DriverLocations { get; set; }
    }
}
