//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.SalaryMasters = new HashSet<SalaryMaster>();
        }
    
        public int Id { get; set; }
        public bool IsDeleted { get; set; }
        public string EmployeetName { get; set; }
        public string MobileNumber { get; set; }
        public string EmailId { get; set; }
        public string EmployeeAddress { get; set; }
        public double Salary { get; set; }
        public string EmployeeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalaryMaster> SalaryMasters { get; set; }
    }
}
