//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class FraAddVehicleType
    {
        public int Id { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public Nullable<int> VehicleType_Id { get; set; }
        public string Status { get; set; }
        public Nullable<int> Admin_LoginId { get; set; }
    }
}
