//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthBooking
    {
        public int Id { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> Test_Id { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public Nullable<int> Slotid { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual HealthCheckUp HealthCheckUp { get; set; }
    }
}
