//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthCheckupCenter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HealthCheckupCenter()
        {
            this.CheckUpReports = new HashSet<CheckUpReport>();
            this.CmpltCheckUps = new HashSet<CmpltCheckUp>();
            this.HealthCheckUps = new HashSet<HealthCheckUp>();
            this.HealthPayOuts = new HashSet<HealthPayOut>();
            this.HealthCheckUpPackages = new HashSet<HealthCheckUpPackage>();
        }
    
        public int Id { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsApproved { get; set; }
        public string LabName { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public string LicenceImage { get; set; }
        public string LicenceNumber { get; set; }
        public int StateMaster_Id { get; set; }
        public int CityMaster_Id { get; set; }
        public string Location { get; set; }
        public int AdminLogin_Id { get; set; }
        public string PAN { get; set; }
        public string GSTNumber { get; set; }
        public string AadharImage { get; set; }
        public string AadharNumber { get; set; }
        public int Location_Id { get; set; }
        public Nullable<int> Vendor_Id { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string RegNo { get; set; }
        public string RegImage { get; set; }
        public string Pincode { get; set; }
        public string HealthCheckUpId { get; set; }
        public Nullable<bool> IsCheckedTermsCondition { get; set; }
        public Nullable<System.TimeSpan> StateTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public string RefId { get; set; }
        public string year { get; set; }
        public string About { get; set; }
        public string HealthType { get; set; }
    
        public virtual AdminLogin AdminLogin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckUpReport> CheckUpReports { get; set; }
        public virtual CityMaster CityMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CmpltCheckUp> CmpltCheckUps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HealthCheckUp> HealthCheckUps { get; set; }
        public virtual StateMaster StateMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HealthPayOut> HealthPayOuts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HealthCheckUpPackage> HealthCheckUpPackages { get; set; }
    }
}
