//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthCheckUpPackage
    {
        public int Id { get; set; }
        public Nullable<int> packageId { get; set; }
        public Nullable<double> TestAmt { get; set; }
        public Nullable<int> CenterId { get; set; }
        public Nullable<double> DiscountAmt { get; set; }
        public Nullable<int> Gst { get; set; }
    
        public virtual HealthCheckupCenter HealthCheckupCenter { get; set; }
    }
}
