//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthCheckUp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HealthCheckUp()
        {
            this.CmpltCheckUps = new HashSet<CmpltCheckUp>();
            this.HealthBookings = new HashSet<HealthBooking>();
        }
    
        public int Id { get; set; }
        public int Center_Id { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> PackageId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CmpltCheckUp> CmpltCheckUps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HealthBooking> HealthBookings { get; set; }
        public virtual HealthCheckupCenter HealthCheckupCenter { get; set; }
    }
}
