//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalNurse
    {
        public int Id { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string NurseName { get; set; }
        public Nullable<int> NurseType_Id { get; set; }
        public Nullable<int> Hospital_Id { get; set; }
    
        public virtual NurseType NurseType { get; set; }
        public virtual Hospital Hospital { get; set; }
    }
}
