//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospital
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hospital()
        {
            this.HospitalNurses = new HashSet<HospitalNurse>();
            this.HospitalReports = new HashSet<HospitalReport>();
            this.PatientAppointments = new HashSet<PatientAppointment>();
            this.PatientAppointments1 = new HashSet<PatientAppointment>();
        }
    
        public int Id { get; set; }
        public bool IsDeleted { get; set; }
        public string HospitalName { get; set; }
        public int StateMaster_Id { get; set; }
        public int CityMaster_Id { get; set; }
        public string Location { get; set; }
        public string AuthorizationLetterImage { get; set; }
        public string Password { get; set; }
        public bool IsApproved { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailId { get; set; }
        public string MobileNumber { get; set; }
        public int AdminLogin_Id { get; set; }
        public int Location_Id { get; set; }
        public Nullable<int> Vendor_Id { get; set; }
        public string PinCode { get; set; }
        public string HospitalId { get; set; }
        public Nullable<bool> IsCheckedTermsCondition { get; set; }
        public string RefId { get; set; }
    
        public virtual AdminLogin AdminLogin { get; set; }
        public virtual CityMaster CityMaster { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalNurse> HospitalNurses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalReport> HospitalReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientAppointment> PatientAppointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientAppointment> PatientAppointments1 { get; set; }
        public virtual StateMaster StateMaster { get; set; }
    }
}
