//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalDoctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HospitalDoctor()
        {
            this.CancelledAppointments = new HashSet<CancelledAppointment>();
            this.CancelledAppointments1 = new HashSet<CancelledAppointment>();
            this.PatientAppointments = new HashSet<PatientAppointment>();
            this.PatientAppointments1 = new HashSet<PatientAppointment>();
        }
    
        public int Id { get; set; }
        public bool IsDeleted { get; set; }
        public string DoctorName { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string EmailId { get; set; }
        public int StateMaster_Id { get; set; }
        public int CityMaster_Id { get; set; }
        public string Location { get; set; }
        public string LicenceImage { get; set; }
        public string LicenceNumber { get; set; }
        public string ClinicName { get; set; }
        public int Department_Id { get; set; }
        public int Specialist_Id { get; set; }
        public bool IsApproved { get; set; }
        public string PAN { get; set; }
        public string AadharNumber { get; set; }
        public string AadharImage { get; set; }
        public int Hospital_Id { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<int> SlotTime { get; set; }
        public Nullable<double> Fee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CancelledAppointment> CancelledAppointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CancelledAppointment> CancelledAppointments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientAppointment> PatientAppointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientAppointment> PatientAppointments1 { get; set; }
    }
}
