//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lab()
        {
            this.BookTestLabs = new HashSet<BookTestLab>();
            this.LabPayOuts = new HashSet<LabPayOut>();
            this.LabReports = new HashSet<LabReport>();
            this.TestLabs = new HashSet<TestLab>();
        }
    
        public int Id { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsApproved { get; set; }
        public string LabName { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public string LicenceImage { get; set; }
        public string LicenceNumber { get; set; }
        public int StateMaster_Id { get; set; }
        public int CityMaster_Id { get; set; }
        public string Location { get; set; }
        public int AdminLogin_Id { get; set; }
        public string PAN { get; set; }
        public string GSTNumber { get; set; }
        public string PanImage { get; set; }
        public string AadharNumber { get; set; }
        public int Location_Id { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<int> Vendor_Id { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<int> HospitalId { get; set; }
        public string lABId { get; set; }
        public Nullable<bool> IsCheckedTermsCondition { get; set; }
        public string RefId { get; set; }
        public string About { get; set; }
        public string LabTypeName { get; set; }
        public string year { get; set; }
        public Nullable<System.DateTime> ChooseDate { get; set; }
        public Nullable<double> fee { get; set; }
        public string WorkingDay { get; set; }
        public string PinCode { get; set; }
        public string image { get; set; }
        public Nullable<int> LabTest_Id { get; set; }
        public Nullable<bool> IsBankUpdateApproved { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookTestLab> BookTestLabs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabPayOut> LabPayOuts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabReport> LabReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestLab> TestLabs { get; set; }
    }
}
