//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabBooking
    {
        public int Id { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> Test_Id { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> TestId { get; set; }
        public Nullable<int> Test { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public Nullable<System.TimeSpan> AvailabelTime1 { get; set; }
        public Nullable<System.TimeSpan> AvailabelTime2 { get; set; }
    
        public virtual BookTestLab BookTestLab { get; set; }
        public virtual TestLab TestLab { get; set; }
        public virtual LabTest LabTest { get; set; }
    }
}
