//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineOrder
    {
        public int Id { get; set; }
        public System.DateTime OrderDate { get; set; }
        public bool IsPaid { get; set; }
        public bool IsDelivered { get; set; }
        public int Patient_Id { get; set; }
        public int Chemist_Id { get; set; }
        public string Name { get; set; }
        public string MobileNumber { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<int> StateMaster_Id { get; set; }
        public string PinCode { get; set; }
        public Nullable<int> CityMaster_Id { get; set; }
        public string OrderId { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<int> Location_Id { get; set; }
        public string DeliveryStatus { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string Remarks { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> finalPrice { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
