//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public int Id { get; set; }
        public string MedicineName { get; set; }
        public string MedicineDescription { get; set; }
        public Nullable<int> MedicineType_Id { get; set; }
        public bool IsDeleted { get; set; }
        public double MRP { get; set; }
        public string BrandName { get; set; }
    }
}
