//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicinePrescriptionDetail
    {
        public int Id { get; set; }
        public Nullable<int> Doctor_Id { get; set; }
        public Nullable<int> Patient_Id { get; set; }
        public string Weight { get; set; }
        public string PresentComplaint { get; set; }
        public string Allergies { get; set; }
        public string Primarydiagnosis { get; set; }
        public string MedicineName1 { get; set; }
        public string Dosage1 { get; set; }
        public string Instruction1 { get; set; }
        public string MedicineName2 { get; set; }
        public string Dosage2 { get; set; }
        public string Instruction2 { get; set; }
        public string MedicineName3 { get; set; }
        public string Dosage3 { get; set; }
        public string Instruction3 { get; set; }
        public string MedicineName4 { get; set; }
        public string Dosage4 { get; set; }
        public string Instruction4 { get; set; }
        public string MedicineName5 { get; set; }
        public string Dosage5 { get; set; }
        public string Instruction5 { get; set; }
        public string MedicineName6 { get; set; }
        public string Dosage6 { get; set; }
        public string Instruction6 { get; set; }
        public string TestPrescribed { get; set; }
        public string MedicineName7 { get; set; }
        public string Dosage7 { get; set; }
        public string Instruction7 { get; set; }
        public string MedicineName8 { get; set; }
        public string Dosage8 { get; set; }
        public string Instruction8 { get; set; }
        public string MedicineName9 { get; set; }
        public string Dosage9 { get; set; }
        public string Instruction9 { get; set; }
        public string MedicineName10 { get; set; }
        public string Dosage10 { get; set; }
        public string Instruction10 { get; set; }
        public string PastMedical_SurgicalHistory { get; set; }
        public string Furtherrefferal_Recommendations { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
