//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nurse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nurse()
        {
            this.NursePayouts = new HashSet<NursePayout>();
        }
    
        public int Id { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsApproved { get; set; }
        public string NurseName { get; set; }
        public string MobileNumber { get; set; }
        public string EmailId { get; set; }
        public string CertificateImage { get; set; }
        public string CertificateNumber { get; set; }
        public string Password { get; set; }
        public int StateMaster_Id { get; set; }
        public int CityMaster_Id { get; set; }
        public string Location { get; set; }
        public int AdminLogin_Id { get; set; }
        public string PAN { get; set; }
        public string AadharNumber { get; set; }
        public string AadharImage { get; set; }
        public bool IsVerifiedByPolice { get; set; }
        public string VerificationDoc { get; set; }
        public Nullable<int> NurseType_Id { get; set; }
        public double Fee { get; set; }
        public string PinCode { get; set; }
        public Nullable<int> Vendor_Id { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string NurseImage { get; set; }
        public string PanImage { get; set; }
        public Nullable<decimal> HrsFeex24 { get; set; }
        public Nullable<decimal> MonthFee { get; set; }
        public string CityName { get; set; }
        public string NurseId { get; set; }
        public Nullable<bool> IsCheckedTermsCondition { get; set; }
        public Nullable<int> Hospital_Id { get; set; }
        public byte[] Data { get; set; }
        public string ContentType { get; set; }
        public string FileName { get; set; }
        public string RefId { get; set; }
        public Nullable<int> experience { get; set; }
        public string about { get; set; }
        public string ClinicName { get; set; }
        public Nullable<int> Location_id { get; set; }
    
        public virtual AdminLogin AdminLogin { get; set; }
        public virtual CityMaster CityMaster { get; set; }
        public virtual StateMaster StateMaster { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NursePayout> NursePayouts { get; set; }
    }
}
