//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class NurseComplaint
    {
        public int ID { get; set; }
        public string Subjects { get; set; }
        public string Complaints { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsResolved { get; set; }
        public string Others { get; set; }
        public Nullable<int> Login_Id { get; set; }
    
        public virtual AdminLogin AdminLogin { get; set; }
    }
}
