//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.BookTestLabs = new HashSet<BookTestLab>();
            this.CancelledAppointments = new HashSet<CancelledAppointment>();
            this.CheckUpReports = new HashSet<CheckUpReport>();
            this.CmpltCheckUps = new HashSet<CmpltCheckUp>();
            this.DoctorReports = new HashSet<DoctorReport>();
            this.HealthBookings = new HashSet<HealthBooking>();
            this.HospitalReports = new HashSet<HospitalReport>();
            this.LabReports = new HashSet<LabReport>();
            this.PatientAppointments = new HashSet<PatientAppointment>();
            this.PatientRequests = new HashSet<PatientRequest>();
            this.TravelMasters = new HashSet<TravelMaster>();
            this.TravelRecordMasters = new HashSet<TravelRecordMaster>();
        }
    
        public int Id { get; set; }
        public string PatientName { get; set; }
        public string EmailId { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<int> StateMaster_Id { get; set; }
        public Nullable<int> CityMaster_Id { get; set; }
        public string Location { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsApproved { get; set; }
        public int AdminLogin_Id { get; set; }
        public Nullable<int> Rwa_Id { get; set; }
        public Nullable<System.DateTime> Reg_Date { get; set; }
        public string PinCode { get; set; }
        public string PatientRegNo { get; set; }
        public Nullable<bool> IsCheckedTermsCondition { get; set; }
        public Nullable<int> vendorId { get; set; }
        public string RefId { get; set; }
        public Nullable<decimal> walletAmount { get; set; }
        public string Password { get; set; }
        public string About { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookTestLab> BookTestLabs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CancelledAppointment> CancelledAppointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckUpReport> CheckUpReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CmpltCheckUp> CmpltCheckUps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorReport> DoctorReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HealthBooking> HealthBookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalReport> HospitalReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabReport> LabReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientAppointment> PatientAppointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientRequest> PatientRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelMaster> TravelMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelRecordMaster> TravelRecordMasters { get; set; }
    }
}
