//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientRequest
    {
        public int Id { get; set; }
        public Nullable<int> Patient_Id { get; set; }
        public Nullable<int> VehicelType_Id { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longtitude { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> Request { get; set; }
        public Nullable<double> DropLatitude { get; set; }
        public Nullable<double> DropLongtitude { get; set; }
        public Nullable<int> StatusKey { get; set; }
    
        public virtual VehicleType VehicleType { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
