//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientAppointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientAppointment()
        {
            this.CancelledAppointments = new HashSet<CancelledAppointment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Patient_Id { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<System.TimeSpan> StartSlotTime { get; set; }
        public Nullable<System.TimeSpan> EndSlotTime { get; set; }
        public Nullable<int> Doctor_Id { get; set; }
        public Nullable<int> Specialist_Id { get; set; }
        public Nullable<bool> IsBooked { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> Hospital_Id { get; set; }
        public Nullable<int> HospitalDoc_Id { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public string WorkingShift { get; set; }
        public Nullable<int> Slot_id { get; set; }
        public Nullable<double> TotalFee { get; set; }
        public Nullable<int> BookingMode_Id { get; set; }
        public string InvoiceNumber { get; set; }
        public string OrderId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<bool> AppointmentIsDone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CancelledAppointment> CancelledAppointments { get; set; }
        public virtual HospitalDoctor HospitalDoctor { get; set; }
        public virtual HospitalDoctor HospitalDoctor1 { get; set; }
        public virtual Specialist Specialist { get; set; }
        public virtual Specialist Specialist1 { get; set; }
        public virtual Hospital Hospital { get; set; }
        public virtual Hospital Hospital1 { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
