//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PenaltyAmount
    {
        public int Id { get; set; }
        public Nullable<int> Pro_Id { get; set; }
        public Nullable<int> Patient_Id { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> UserWalletAmount { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
    }
}
