//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescriptionAppointment
    {
        public int Id { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsAppointment { get; set; }
        public string PreferredAppointmentDateTime1 { get; set; }
        public string PreferredAppointmentDateTime2 { get; set; }
        public string PreferredAppointmentDateTime3 { get; set; }
        public string HospitalName { get; set; }
        public string DoctorName { get; set; }
        public string DoctorSpeciality { get; set; }
        public string DoctorCode { get; set; }
        public string RegistrationNumber { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string AppointmentHour1 { get; set; }
        public string AppointmentMin1 { get; set; }
        public string AppointmentHour2 { get; set; }
        public string AppointmentMin2 { get; set; }
        public string AppointmentHour3 { get; set; }
        public string AppointmentMin3 { get; set; }
        public Nullable<int> Doctor_Id { get; set; }
    }
}
