//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RWA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RWA()
        {
            this.RwaPayouts = new HashSet<RwaPayout>();
        }
    
        public int Id { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsApproved { get; set; }
        public string AuthorityName { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public int StateMaster_Id { get; set; }
        public int CityMaster_Id { get; set; }
        public string Location { get; set; }
        public int AdminLogin_Id { get; set; }
        public string CertificateImage { get; set; }
        public Nullable<int> Vendor_Id { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string RWAId { get; set; }
        public Nullable<bool> IsCheckedTermsCondition { get; set; }
        public string Pincode { get; set; }
        public string LandlineNumber { get; set; }
        public string CertificateNo { get; set; }
        public string About { get; set; }
        public string PAN { get; set; }
        public Nullable<bool> IsBankUpdateApproved { get; set; }
    
        public virtual AdminLogin AdminLogin { get; set; }
        public virtual CityMaster CityMaster { get; set; }
        public virtual StateMaster StateMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RwaPayout> RwaPayouts { get; set; }
    }
}
