//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RWA_PaymentReport
    {
        public int Id { get; set; }
        public Nullable<int> RWA_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Bank_Id { get; set; }
        public string Payment_Id { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<System.TimeSpan> PaymentTime { get; set; }
        public Nullable<bool> PaymentStatus { get; set; }
    }
}
