//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestInLab
    {
        public int Id { get; set; }
        public Nullable<int> Lab_Id { get; set; }
        public Nullable<int> Test_Id { get; set; }
    }
}
