//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestLab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestLab()
        {
            this.LabBookings = new HashSet<LabBooking>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Test_Id { get; set; }
        public Nullable<int> Lab_Id { get; set; }
        public Nullable<double> TestAmount { get; set; }
        public string TestDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabBooking> LabBookings { get; set; }
        public virtual LabTest LabTest { get; set; }
        public virtual Lab Lab { get; set; }
    }
}
