//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelRecordMaster
    {
        public int Id { get; set; }
        public Nullable<int> Patient_Id { get; set; }
        public Nullable<int> Driver_Id { get; set; }
        public Nullable<double> Lat_PickUp_Patient { get; set; }
        public Nullable<double> Lang_PickUp_Pateint { get; set; }
        public Nullable<double> Lang_Drop { get; set; }
        public Nullable<double> Lat_Drop { get; set; }
        public string PickUp_Place { get; set; }
        public string Drop_Place { get; set; }
        public Nullable<int> Vehicle_Id { get; set; }
        public Nullable<bool> IsDriveCompleted { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> Distance { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<decimal> FullAmount { get; set; }
        public Nullable<int> RecordId { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<System.TimeSpan> RideStartTime { get; set; }
        public Nullable<System.TimeSpan> RideEndTime { get; set; }
        public Nullable<bool> Is8HourRide { get; set; }
        public Nullable<double> ExtraCharges { get; set; }
        public string CancelBy { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
