//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelMaster
    {
        public int Id { get; set; }
        public Nullable<int> VehicleType_Id { get; set; }
        public Nullable<int> Patient_Id { get; set; }
        public Nullable<int> Driver_Id { get; set; }
        public Nullable<double> Lat_Driver { get; set; }
        public Nullable<double> Lang_Driver { get; set; }
        public Nullable<int> Vehicle_Id { get; set; }
        public Nullable<bool> IsDriveCompleted { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<bool> DriverKey { get; set; }
        public Nullable<int> StatusKey { get; set; }
    
        public virtual VehicleType VehicleType { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
