//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserWallet
    {
        public int Id { get; set; }
        public Nullable<int> AdminId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<double> Amount { get; set; }
        public string TransactionType { get; set; }
        public Nullable<decimal> walletAmount { get; set; }
    }
}
