//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleAllotHistory
    {
        public int Id { get; set; }
        public Nullable<int> Driver_Id { get; set; }
        public Nullable<int> Vehicle_Id { get; set; }
        public Nullable<System.DateTime> AllocateDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
