//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.TravelMasters = new HashSet<TravelMaster>();
            this.Drivers = new HashSet<Driver>();
            this.TravelRecordMasters = new HashSet<TravelRecordMaster>();
        }
    
        public int Id { get; set; }
        public bool IsDeleted { get; set; }
        public string VehicleNumber { get; set; }
        public Nullable<System.DateTime> Validity { get; set; }
        public Nullable<System.DateTime> InsurranceDate { get; set; }
        public Nullable<System.DateTime> PollutionDate { get; set; }
        public bool IsApproved { get; set; }
        public int VehicleType_Id { get; set; }
        public Nullable<int> Driver_Id { get; set; }
        public Nullable<int> Vendor_Id { get; set; }
        public Nullable<System.DateTime> FitnessCertificateValidity { get; set; }
        public string InsuranceImage { get; set; }
        public string PollutionImage { get; set; }
        public string FitnessCerficateImage { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string RC_Image { get; set; }
        public string RC_No { get; set; }
        public string VehicleName { get; set; }
        public string VehicleImg { get; set; }
        public string AccountNo { get; set; }
        public string IFSCCode { get; set; }
        public string BranchName { get; set; }
        public string BranchAddress { get; set; }
        public string HolderName { get; set; }
        public string CancelCheque { get; set; }
        public Nullable<double> DriverCharges { get; set; }
        public string AccountHolderName { get; set; }
        public string RefId { get; set; }
        public Nullable<int> VehicleCat_Id { get; set; }
        public string VehicleOwnerName { get; set; }
        public string PAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelMaster> TravelMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Driver> Drivers { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelRecordMaster> TravelRecordMasters { get; set; }
    }
}
