//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPortal.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendor()
        {
            this.Hospitals = new HashSet<Hospital>();
            this.Vehicles = new HashSet<Vehicle>();
            this.VendorPayOuts = new HashSet<VendorPayOut>();
            this.Nurses = new HashSet<Nurse>();
            this.Chemists = new HashSet<Chemist>();
        }
    
        public int Id { get; set; }
        public bool IsDeleted { get; set; }
        public string CompanyName { get; set; }
        public string MobileNumber { get; set; }
        public string EmailId { get; set; }
        public int StateMaster_Id { get; set; }
        public int City_Id { get; set; }
        public string Location { get; set; }
        public string GSTNumber { get; set; }
        public string Password { get; set; }
        public bool IsApproved { get; set; }
        public int AdminLogin_Id { get; set; }
        public string VendorName { get; set; }
        public string AadharOrPANNumber { get; set; }
        public string AadharOrPANImage { get; set; }
        public string PanImage { get; set; }
        public string PanNumber { get; set; }
        public string AadharOrPANImage2 { get; set; }
        public string UniqueId { get; set; }
        public Nullable<bool> IsCheckedTermsCondition { get; set; }
        public string PinCode { get; set; }
        public string About { get; set; }
        public Nullable<bool> IsBankUpdateApproved { get; set; }
    
        public virtual AdminLogin AdminLogin { get; set; }
        public virtual CityMaster CityMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hospital> Hospitals { get; set; }
        public virtual StateMaster StateMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle> Vehicles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorPayOut> VendorPayOuts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nurse> Nurses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chemist> Chemists { get; set; }
    }
}
